name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.0
  encrypt: ^5.0.1
  equatable: ^2.0.3
  firebase_crashlytics: ^2.3.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  sqflite_sqlcipher: ^2.1.0
  # sqflite: ^2.0.0+3

  movie:
    path: ../movie
  search:
    path: ../search
  tvseries:
    path: ../tvseries

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.0.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  mockito: ^5.0.8
  mocktail: ^0.2.0

flutter:
